quarkus.application.name=device-registry
quarkus.application.version=0.1.0
quarkus.http.port=8082
quarkus.grpc.server.port=9002

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fleetiq
quarkus.datasource.password=fleetiq_dev
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/device_registry_db
quarkus.datasource.reactive.url=postgresql://localhost:5432/device_registry_db
quarkus.datasource.reactive.max-size=10

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.otel.exporter.otlp.endpoint=http://localhost:4319
quarkus.otel.service.name=device-registry

quarkus.log.level=INFO
quarkus.log.category."io.fleetiq".level=DEBUG
