apiVersion: v1
kind: ConfigMap
metadata:
  name: device-registry-config
  namespace: fleetiq
data:
  application.properties: |
    quarkus.application.name=device-registry
    quarkus.http.port=8082
    quarkus.grpc.server.port=9002
    quarkus.datasource.jdbc=false
    quarkus.datasource.reactive.url=jdbc:postgresql://postgres.fleetiq.svc.cluster.local:5432/device_registry_db
    quarkus.flyway.migrate-at-start=true
    quarkus.otel.exporter.otlp.endpoint=http://otel-collector.fleetiq.svc.cluster.local:4317
    quarkus.otel.service.name=device-registry
