apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
        tags: []
      tracesToMetrics:
        datasourceUid: prometheus
        queries:
          - name: "Request Rate"
            query: "sum(rate(http_server_requests_seconds_count{service='$${__tags['service.name']}'}[5m]))"
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: 'traceId":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'
