apiVersion: v1
kind: Service
metadata:
  name: pekko-cluster-headless
  namespace: fleetiq
  labels:
    app: pekko-cluster
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: pekko-cluster
  ports:
    - port: 2551
      targetPort: 2551
      name: remoting
    - port: 8558
      targetPort: 8558
      name: management
  publishNotReadyAddresses: true
