package io.fleetiq.device.domain.model;

import java.time.Instant;
import java.util.Map;

public record Device(
    String vin,
    String deviceType,
    String manufacturer,
    String model,
    int year,
    Map<String, String> capabilities,
    DeviceStatus status,
    Instant registeredAt,
    Instant updatedAt
) {

    /**
     * Factory method for creating a brand-new device registration.
     * Enforces domain defaults (IDLE status) and leaves DB-managed fields empty.
     */
    public static Device registerNew(
        String vin,
        String deviceType,
        String manufacturer,
        String model,
        int year,
        Map<String, String> capabilities
    ) {
        return new Device(
            vin,
            deviceType,
            manufacturer,
            model,
            year,
            capabilities,
            DeviceStatus.IDLE, // Default status enforced by Domain
            null,              // Generated by Hibernate on save
            null               // Generated by Hibernate on save
        );
    }
}
