package io.fleetiq.device.domain.model;

import java.time.Instant;
import java.util.Map;
import java.util.regex.Pattern;

public record Device(
    String vin,
    String deviceType,
    String manufacturer,
    String model,
    int year,
    Map<String, String> capabilities,
    DeviceStatus status,
    Instant registeredAt,
    Instant updatedAt
) {

    private static final Pattern VIN_PATTERN = Pattern.compile("[A-HJ-NPR-Z0-9]{17}");

    /**
     * Factory method for creating a brand-new device registration.
     * Enforces domain defaults (IDLE status) and leaves DB-managed fields empty.
     */
    public static Device registerNew(
        String vin,
        String deviceType,
        String manufacturer,
        String model,
        int year,
        Map<String, String> capabilities,
        int currentYear
    ) {
        validateVin(vin);
        requireText(deviceType, "Device type");
        requireText(manufacturer, "Manufacturer");
        requireText(model, "Model");
        if (year < 1886 || year > currentYear + 1) {
            throw new DeviceValidationException("Year must be between 1886 and " + (currentYear + 1));
        }
        return new Device(
            vin,
            deviceType,
            manufacturer,
            model,
            year,
            capabilities == null ? Map.of() : Map.copyOf(capabilities),
            DeviceStatus.IDLE, // Default status enforced by Domain
            null,              // Generated by Hibernate on save
            null               // Generated by Hibernate on save
        );
    }

    public static String validateVin(String vin) {
        if (vin == null || !VIN_PATTERN.matcher(vin).matches()) {
            throw new DeviceValidationException("VIN must contain 17 characters and exclude I, O and Q");
        }
        return vin;
    }

    private static void requireText(String value, String field) {
        if (value == null || value.isBlank()) {
            throw new DeviceValidationException(field + " is required");
        }
    }
}
